# Generated by Django 5.0.1 on 2024-02-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0005_alter_userprofile_num_of_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gas',
            fields=[
                ('Gid', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
