# Generated by Django 5.0.1 on 2024-02-29 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0007_product_delete_gas_remove_userprofile_num_of_orders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('amount', models.FloatField()),
                ('order_status', models.CharField(max_length=50)),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField(null=True)),
                ('pay_mode', models.CharField(max_length=50)),
                ('pay_status', models.CharField(max_length=50)),
                ('Gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gas.product')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
